In [15]:
import pandas as pd 

df = pd.read_csv('./201707_201801.csv', encoding='cp949')

df

,year,format: day,hour,신갈동_강수,신갈동_기온,중앙동_강수,중앙동_기온,죽전동_강수,죽전동_기온
0,201707,1,0.0,0.0,24.900000,0.0,23.700001,0.0,24.200001
1,201707,1,100.0,0.0,26.200001,0.0,25.200001,0.0,25.299999
2,201707,1,200.0,0.0,27.000000,0.0,26.100000,0.0,26.100000
3,201707,1,300.0,0.0,27.299999,0.0,26.600000,0.0,26.700001
4,201707,1,400.0,0.0,27.200001,0.0,26.500000,0.0,27.100000
5,201707,1,500.0,0.0,26.600000,0.0,26.299999,0.0,26.500000
6,201707,1,600.0,0.1,24.600000,0.2,23.799999,0.0,25.100000
7,201707,1,700.0,2.2,23.400000,3.1,23.100000,0.4,23.500000
8,201707,1,800.0,2.5,23.100000,1.7,23.100000,5.0,22.700001
9,201707,1,900.0,1.3,23.500000,0.5,23.200001,6.3,22.600000
10,201707,1,1000.0,0.0,23.700001,0.1,23.000000,0.1,22.500000
11,201707,1,1100.0,0.1,23.900000,0.1,22.900000,0.1,22.400000
12,201707,1,1200.0,0.2,23.900000,0.1,23.200001,0.1,22.700001
13,201707,1,1300.0,0.3,23.900000,0.4,23.500000,0.1,23.000000
14,201707,1,1400.0,2.0,23.799999,1.5,23.700001,0.0,23.900000
15,201707,1,1500.0,1.6,23.900000,0.5,23.799999,2.6,23.900000
16,201707,1,1600.0,0.6,24.000000,0.5,23.700001,0.8,24.299999
17,201707,1,1700.0,0.4,24.000000,0.3,23.600000,0.6,24.500000
18,201707,1,1800.0,0.3,23.900000,0.4,23.600000,0.0,24.200001
19,201707,1,1900.0,0.4,23.900000,0.1,23.500000,0.0,23.700001
20,201707,1,2000.0,0.2,23.900000,0.1,24.000000,0.0,23.400000
21,201707,1,2100.0,0.1,24.299999,0.1,24.200001,0.0,23.400000
22,201707,1,2200.0,0.1,24.900000,0.2,24.799999,0.0,23.600000
23,201707,1,2300.0,0.2,25.600000,0.1,25.400000,0.0,23.799999
24,201707,2,0.0,1.7,25.299999,2.2,25.000000,0.4,24.100000
25,201707,2,100.0,0.3,26.000000,0.4,26.200001,1.5,24.100000
26,201707,2,200.0,0.1,26.400000,0.2,26.400000,0.5,24.799999
27,201707,2,300.0,0.2,26.799999,0.2,26.900000,0.3,25.000000
28,201707,2,400.0,1.2,26.000000,0.4,26.900000,0.1,24.600000
29,201707,2,500.0,1.2,26.299999,0.0,27.100000,0.0,24.500000
...,...,...,...,...,...,...,...,...,...
5136,201801,30,1800.0,0.0,-2.300000,0.0,-0.800000,0.0,-1.600000
5137,201801,30,1900.0,0.0,-3.300000,0.0,-1.800000,0.0,-2.800000
5138,201801,30,2000.0,0.0,-4.000000,0.0,-4.400000,0.0,-3.500000
5139,201801,30,2100.0,0.0,-4.600000,0.0,-5.400000,0.0,-4.100000
5140,201801,30,2200.0,0.0,-4.500000,0.0,-5.400000,0.0,-4.100000
5141,201801,30,2300.0,0.0,-2.700000,0.0,-3.500000,0.0,-2.200000
5142,201801,31,0.0,0.0,-1.200000,0.0,-1.400000,0.0,-1.200000
5143,201801,31,100.0,0.0,-0.700000,0.0,-0.600000,0.0,-0.800000
5144,201801,31,200.0,0.0,-0.300000,0.0,0.000000,0.0,-0.700000
5145,201801,31,300.0,0.0,-0.200000,0.0,0.000000,0.0,-0.400000
5146,201801,31,400.0,0.0,-0.400000,0.0,-0.100000,0.0,-0.600000
5147,201801,31,500.0,0.0,-0.400000,0.0,-0.300000,0.0,-0.500000
5148,201801,31,600.0,0.0,-0.200000,0.0,-0.200000,0.0,-0.200000
5149,201801,31,700.0,0.0,-0.500000,0.0,-0.800000,0.0,-0.400000
5150,201801,31,800.0,0.0,-1.100000,0.0,-1.800000,0.0,-1.200000
5151,201801,31,900.0,0.0,-1.500000,0.0,-2.300000,0.0,-1.600000
5152,201801,31,1000.0,0.0,-2.000000,0.0,-2.400000,0.0,-2.100000
5153,201801,31,1100.0,0.0,-2.400000,0.0,-2.900000,0.0,-2.500000
5154,201801,31,1200.0,0.0,-3.400000,0.0,-3.600000,0.0,-3.500000
5155,201801,31,1300.0,0.0,-4.700000,0.0,-4.700000,0.0,-4.700000
5156,201801,31,1400.0,0.0,-5.300000,0.0,-5.500000,0.0,-5.700000
5157,201801,31,1500.0,0.0,-5.800000,0.0,-6.200000,0.0,-6.300000
5158,201801,31,1600.0,0.0,-6.300000,0.0,-6.700000,0.0,-6.800000
5159,201801,31,1700.0,0.0,-6.800000,0.0,-7.100000,0.0,-7.400000
5160,201801,31,1800.0,0.0,-7.300000,0.0,-7.900000,0.0,-7.800000
5161,201801,31,1900.0,0.0,-7.800000,0.0,-8.500000,0.0,-8.100000
5162,201801,31,2000.0,0.0,-7.700000,0.0,-8.700000,0.0,-8.300000
5163,201801,31,2100.0,0.0,-8.200000,0.0,-9.300000,0.0,-8.300000
5164,201801,31,2200.0,0.0,-7.600000,0.0,-8.700000,0.0,-7.400000
5165,201801,31,2300.0,0.0,-5.100000,0.0,-6.200000,0.0,-4.500000

In [17]:
df = df.drop(columns=[' format: day', 'hour'], axis=1)
df

        year  신갈동_강수     신갈동_기온  중앙동_강수     중앙동_기온  죽전동_강수     죽전동_기온
0     201707     0.0  24.900000     0.0  23.700001     0.0  24.200001
1     201707     0.0  26.200001     0.0  25.200001     0.0  25.299999
2     201707     0.0  27.000000     0.0  26.100000     0.0  26.100000
3     201707     0.0  27.299999     0.0  26.600000     0.0  26.700001
4     201707     0.0  27.200001     0.0  26.500000     0.0  27.100000
5     201707     0.0  26.600000     0.0  26.299999     0.0  26.500000
6     201707     0.1  24.600000     0.2  23.799999     0.0  25.100000
7     201707     2.2  23.400000     3.1  23.100000     0.4  23.500000
8     201707     2.5  23.100000     1.7  23.100000     5.0  22.700001
9     201707     1.3  23.500000     0.5  23.200001     6.3  22.600000
10    201707     0.0  23.700001     0.1  23.000000     0.1  22.500000
11    201707     0.1  23.900000     0.1  22.900000     0.1  22.400000
12    201707     0.2  23.900000     0.1  23.200001     0.1  22.700001
13    201707     0.3  23.900000     0.4  23.500000     0.1  23.000000
14    201707     2.0  23.799999     1.5  23.700001     0.0  23.900000
15    201707     1.6  23.900000     0.5  23.799999     2.6  23.900000
16    201707     0.6  24.000000     0.5  23.700001     0.8  24.299999
17    201707     0.4  24.000000     0.3  23.600000     0.6  24.500000
18    201707     0.3  23.900000     0.4  23.600000     0.0  24.200001
19    201707     0.4  23.900000     0.1  23.500000     0.0  23.700001
20    201707     0.2  23.900000     0.1  24.000000     0.0  23.400000
21    201707     0.1  24.299999     0.1  24.200001     0.0  23.400000
22    201707     0.1  24.900000     0.2  24.799999     0.0  23.600000
23    201707     0.2  25.600000     0.1  25.400000     0.0  23.799999
24    201707     1.7  25.299999     2.2  25.000000     0.4  24.100000
25    201707     0.3  26.000000     0.4  26.200001     1.5  24.100000
26    201707     0.1  26.400000     0.2  26.400000     0.5  24.799999
27    201707     0.2  26.799999     0.2  26.900000     0.3  25.000000
28    201707     1.2  26.000000     0.4  26.900000     0.1  24.600000
29    201707     1.2  26.299999     0.0  27.100000     0.0  24.500000
...      ...     ...        ...     ...        ...     ...        ...
5136  201801     0.0  -2.300000     0.0  -0.800000     0.0  -1.600000
5137  201801     0.0  -3.300000     0.0  -1.800000     0.0  -2.800000
5138  201801     0.0  -4.000000     0.0  -4.400000     0.0  -3.500000
5139  201801     0.0  -4.600000     0.0  -5.400000     0.0  -4.100000
5140  201801     0.0  -4.500000     0.0  -5.400000     0.0  -4.100000
5141  201801     0.0  -2.700000     0.0  -3.500000     0.0  -2.200000
5142  201801     0.0  -1.200000     0.0  -1.400000     0.0  -1.200000
5143  201801     0.0  -0.700000     0.0  -0.600000     0.0  -0.800000
5144  201801     0.0  -0.300000     0.0   0.000000     0.0  -0.700000
5145  201801     0.0  -0.200000     0.0   0.000000     0.0  -0.400000
5146  201801     0.0  -0.400000     0.0  -0.100000     0.0  -0.600000
5147  201801     0.0  -0.400000     0.0  -0.300000     0.0  -0.500000
5148  201801     0.0  -0.200000     0.0  -0.200000     0.0  -0.200000
5149  201801     0.0  -0.500000     0.0  -0.800000     0.0  -0.400000
5150  201801     0.0  -1.100000     0.0  -1.800000     0.0  -1.200000
5151  201801     0.0  -1.500000     0.0  -2.300000     0.0  -1.600000
5152  201801     0.0  -2.000000     0.0  -2.400000     0.0  -2.100000
5153  201801     0.0  -2.400000     0.0  -2.900000     0.0  -2.500000
5154  201801     0.0  -3.400000     0.0  -3.600000     0.0  -3.500000
5155  201801     0.0  -4.700000     0.0  -4.700000     0.0  -4.700000
5156  201801     0.0  -5.300000     0.0  -5.500000     0.0  -5.700000
5157  201801     0.0  -5.800000     0.0  -6.200000     0.0  -6.300000
5158  201801     0.0  -6.300000     0.0  -6.700000     0.0  -6.800000
5159  201801     0.0  -6.800000     0.0  -7.100000     0.0  -7.400000
5160  201801     0.0  -7.300000     0.0  -7.900000     0.0  -7.800000
5161  201801     0.0  -7.800000     0.0  -8.500000     0.0  -8.100000
5162  201801     0.0  -7.700000     0.0  -8.700000     0.0  -8.300000
5163  201801     0.0  -8.200000     0.0  -9.300000     0.0  -8.300000
5164  201801     0.0  -7.600000     0.0  -8.700000     0.0  -7.400000
5165  201801     0.0  -5.100000     0.0  -6.200000     0.0  -4.500000

[5166 rows x 7 columns]

In [40]:
df1 = df[df['year']==201801]
df2 = df1[['신갈동_기온', '중앙동_기온', '죽전동_기온']].describe()
df2 = df2.loc[['min', 'max', 'mean']]
df2

         신갈동_기온     중앙동_기온     죽전동_기온
min  -16.799999 -16.900000 -16.200001
max    7.000000   6.700000   7.400000
mean  -3.740591  -4.238978  -3.633468

In [41]:
df3 = df1[['신갈동_강수','중앙동_강수','죽전동_강수']].sum()
df3

신갈동_강수     9.0
중앙동_강수    10.2
죽전동_강수     1.8
dtype: float64